// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOlix5yuN9DiX9cV64SCbCrgbghD2pO2Y',
    appId: '1:296857543204:web:072b2d1a588bb223bbeeb1',
    messagingSenderId: '296857543204',
    projectId: 'pookierih',
    authDomain: 'pookierih.firebaseapp.com',
    storageBucket: 'pookierih.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8GpqPPugOYZeXXvK5xGuDUp5zY9Ylhhw',
    appId: '1:296857543204:android:9b3908bc2632bb96bbeeb1',
    messagingSenderId: '296857543204',
    projectId: 'pookierih',
    storageBucket: 'pookierih.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUcOmVxANWybthp6cFC2IN49rDMFK71M',
    appId: '1:296857543204:ios:4731c45157e35459bbeeb1',
    messagingSenderId: '296857543204',
    projectId: 'pookierih',
    storageBucket: 'pookierih.firebasestorage.app',
    iosBundleId: 'com.example.pookie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkUcOmVxANWybthp6cFC2IN49rDMFK71M',
    appId: '1:296857543204:ios:4731c45157e35459bbeeb1',
    messagingSenderId: '296857543204',
    projectId: 'pookierih',
    storageBucket: 'pookierih.firebasestorage.app',
    iosBundleId: 'com.example.pookie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOlix5yuN9DiX9cV64SCbCrgbghD2pO2Y',
    appId: '1:296857543204:web:9df9f63907be7e04bbeeb1',
    messagingSenderId: '296857543204',
    projectId: 'pookierih',
    authDomain: 'pookierih.firebaseapp.com',
    storageBucket: 'pookierih.firebasestorage.app',
  );
}
